### ISSUE TITLE
Getting "broken dependent from source" when installing sam-cli on Homebrew for Linux

### ISSUE THREAD

**Issue by DanielFrank** [aws/homebrew-tap#130]
Our CI/CD involves installing sam-cli using basically:
```
brew tap aws/tap
brew install aws-sam-cli
```
After installing Homebrew for Linux.

Our last successful build was three days ago ( August 28th). (We didn't try another build until the 31st.)

Today we're getting this:
```
> ==> No outdated dependents to upgrade!
> ==> Checking for dependents of upgraded formulae...
> ==> Reinstalling 1 broken dependent from source:
> aws/tap/aws-sam-cli
```

When the system tries to run `sam --version` , it gets `sam: command not found`

Let me know what other information I can provide.

**Comment by DanielFrank** [comment]
If relevant, a note that I get this issue whether I install from Linuxbrew or from Homebrew...

**Comment by DanielFrank** [comment]
The issue with `sam: command not found` seems to be that we're not soft-linking to `/home/linuxbrew/.linuxbrew/bin/`. Whether that's related to having to do a reinstall, I don't know enough about Homebrew to say.

See the "Orb Install step failed" above for workarounds...

**Comment by DanielFrank** [comment]
Per [here](https://github.com/aws/homebrew-tap/issues/132), the issue may be related to a Homebrew upgrade?

**Comment by DanielFrank** [comment]
Duplicate of #132

**Comment by wchengru** [comment]
Hi @DanielFrank , 

Homebrew is updated to 2.5.0 today, I am using the latest version:
```
$ brew --version
Homebrew 2.5.0
``` 
I tried to repro this issue by installing aws-sam-cli with the following command on Amazon Linux 2 x86_64:
```
$ brew tap aws/tap
$ brew install aws-sam-cli
$ sam --version
```
Now sam cli is installed properly:
```
$ sam --version
SAM CLI, version 1.2.0
```
Can you please confirm that this issue is resolved after installing with Homebrew 2.5.0?

Thanks!

**Comment by DanielFrank** [comment]
I have Homebrew 2.5
```
Homebrew 2.5.0
Homebrew/linuxbrew-core (git revision 860f; last commit 2020-09-08)
```

Still getting the same issue.
```
==> Reinstalling 1 broken dependent from source:
aws/tap/aws-sam-cli
[...]
/bin/bash: line 3: sam: command not found
```

We've found that calling `brew install` twice "fixes" things.

We're calling `Linuxbrew/install` rather than `Homebrew/install` but that doesn't seem to make a difference.

**Comment by cmdcolin** [comment]
I can confirm that doing the brew install twice fixed it for me on Ubuntu 20.10, brew 2.7.0

**Comment by krrenjith** [comment]
Issue persist with Homebrew 2.7.1 and brew install twice fixes the issue.  During first install getting following logs.

==> Installing aws/tap/aws-sam-cli
==> Pouring aws-sam-cli-1.15.0.x86_64_linux.bottle.tar.gz
🍺  /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0: 3,951 files, 87.9MB
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
==> Reinstalling 1 broken dependent from source:
aws/tap/aws-sam-cli
==> Caveats
==> openssl@1.1

However, the path /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0 doesn't get created. The actual path getting created is /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0.reinstall 

After second run of brew install /home/ec2-user/.linuxbrew/Cellar/aws-sam-cli/1.15.0 gets created and everything works as expected.

**Comment by shahabi8** [comment]
I'm getting this issue with brew 3.2.0, is there any solution for it?

**Comment by hoffa** [comment]
Is this still an issue?

I couldn't reproduce this with Linuxbrew in https://github.com/aws/homebrew-tap/issues/189#issuecomment-1003839775.

**Comment by hoffa** [comment]
No activity for a while and couldn't manage to reproduce the issue in any of the similar issues; closing.
